# curl https://api.openai.com/v1/chat/completions
#  -H "Content-Type: application/json"
#  -H "Authorization: Bearer $OPENAI_API_KEY"
#  -d '{
#     "model": "gpt-3.5-turbo",
#     "messages": [{"role": "user", "content": "Say this is a test!"}],
#     "temperature": 0.7
#   }'
POST https://api.openai.com/v1/chat/completions
Authorization: Bearer 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
Content-Type: application/json

{
  "model": "gpt-3.5-turbo",
  "messages": [
    {
      "role": "user",
      "content": "i want to create a daily videogame challenge/trivia app that provides a question from videogame history (characters, easter eggs, whatever) every day to the end users.Create a  10 examples of questions with 4 possible answers and tell me the valid answer. Questions must follow the topic of Game Lore & Storylines and must be from 1990 to present day. All questions should be ranked and grouped by difficulty levels easy, medium or hard.  in order to identify it add the name of the topic at the beggining of the whole response like 'topic:' but avoid adding the timeline in the response."
    }
  ],
  "temperature": 0.7
}

###


# curl -X GET "http://your-api-url/challenges?category=LORE_AND_STORYLINES&difficulty=HARD"
GET http://localhost:8080/challenges?category=LORE_AND_STORYLINES&difficulty=Easy
Content-Type: application/vnd.api+json
###

GET https://api.openai.com/v1/models
Authorization: Bearer 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

