
< {%
    request.variables.set("CATEGORY", "LORE_AND_STORYLINES")
    request.variables.set("DIFFICULTY", "HARD")
%}
GET {{protocol}}{{host}}/challenges?category={{CATEGORY}}&difficulty={{DIFFICULTY}}
Accept: application/json
###


< {%
    request.variables.set("CHALLENGE_ID", "f2579748-24fd-4763-9cd5-24a6e462995b")
%}
POST {{protocol}}{{host}}/challenges/{{CHALLENGE_ID}}/solve
Content-Type: application/json

{
  "userId": "f2579748-24fd-4763-9cd5-24a6e462995b",
  "answers": [
    "Fender",
    "Blades of Chaos",
    "Calamity Ganon",
    "Tyreen Calypso",
    "Miller",
    "Super Mario Bros",
    "Middle-earth: Shadow of Mordor",
    "The Synths",
    "Zanza",
    "The Stranger"
  ]
}
###
