name: PR Workflow

on:
  pull_request:
    branches:
      - '**'

jobs:

  static_code_analysis:
    name: Spotless
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Run spotlessCheck gradle task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            spotlessCheck

  architecture_analysis:
    name: Konsist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Run konsistTest gradle task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            konsistTest

  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up debug logging
        run: echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build with Gradle, run tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            check 
            -x jacocoTestCoverageVerification 
            -x jacocoTestReport
